version: '3.8'

services:
  db:
    image: postgres:16
    container_name: delivery_postgres
    environment:
      POSTGRES_DB: delivery
      POSTGRES_USER: courier_user
      POSTGRES_PASSWORD: qwer52
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - delivery-network

  graphhopper:
    build:
      context: ./graphhopper
    container_name: delivery_graphhopper
    ports:
      - "8989:8989"
    depends_on:
      - db
    networks:
      - delivery-network

  backend:
    build:
      context: .
    container_name: delivery_backend
    command: uvicorn main:app --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"
    expose:
      - "8000"
    volumes:
      - .:/app
    environment:
      DATABASE_URL: postgresql+psycopg2://courier_user:qwer52@db:5432/delivery
    depends_on:
      - db
      - graphhopper
    networks:
      - delivery-network

  admin-frontend:
    build:
      context: ./admin-frontend
    container_name: delivery_admin
    ports:
      - "3000:80"
    networks:
      - delivery-network
    depends_on:
      - backend

  nginx:
    image: nginx:alpine
    container_name: delivery_nginx
    ports:
      - "8001:80"
    volumes:
      # твой конфиг nginx
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro

      # Используем собранную статику React:
      - ./admin-frontend/build:/usr/share/nginx/html:ro

    depends_on:
      - backend
      - admin-frontend
    networks:
      - delivery-network

volumes:
  postgres_data:

networks:
  delivery-network:
    driver: bridge
