version: '3.8'

services:
  db:
    image: postgres:16
    container_name: delivery_postgres
    restart: always
    environment:
      POSTGRES_DB: delivery
      POSTGRES_USER: courier_user
      POSTGRES_PASSWORD: qwer52
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  graphhopper:
    build:
      context: ./graphhopper
    container_name: delivery_graphhopper
    ports:
      - "8989:8989"
    depends_on:
      - db

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: delivery_backend
    command: uvicorn main:app --reload --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      DATABASE_URL: postgresql+psycopg2://courier_user:qwer52@db:5432/delivery
    depends_on:
      - db
      - graphhopper

  frontend:
    image: python:3.11
    container_name: delivery_frontend
    working_dir: /app
    command: python3 -m http.server 8001
    volumes:
      - ./static:/app
    ports:
      - "8001:8001"

volumes:
  postgres_data: